### ISSUE TITLE
Left hand stick on zerovector sometimes

### ISSUE THREAD

**Issue by bamaGit** [oculus-samples/Unreal-HandGameplay#10]
sometimes my left hand stack to bottom without fix, so i Must restart project to fix again

**Comment by jasonmeisel** [comment]
Thank you for the bug report! Could you provide us with any more information? Is there a way to reproduce the issue?

**Comment by jasonmeisel** [comment]
We're closing this for now, but please leave us more information if this is still an issue for you.
