### ISSUE TITLE
How can I open this project in Unreal 5? (Sorry if this is not the proper place to post a question)

### ISSUE THREAD

**Issue by DarioMaciel** [oculus-samples/Unreal-HandGameplay#12]
I tried opening this project in Unreal 5.1 meta branch and it didnt work. It gave me many issues, not only related to Oculus VR/OculusXR, but many others I couldn't solve.
How can I open it properly?

**Comment by Pranavpaharia** [comment]
Same here, it gave me these build error logs.
`1>D:\UEProjects\Unreal-HandGameplay.git\Plugins\OculusUtils\OculusUtils.uplugin : warning : Unknown platform Win32 while parsing allow list for module descriptor OculusUtils
1>Unable to find plugin 'OculusVR' (referenced via default plugins -> OculusHandTools.uplugin). Install it and try again, or remove it from the required plugin list.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command "D:\UnrealEngineOculus\Engine\Build\BatchFiles\Build.bat -Target="HandGameplayEditor Win64 Development -Project=\"D:\UEProjects\Unreal-HandGameplay.git\HandGameplay.uproject\"" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 6.
1>Done building project "HandGameplay.vcxproj" -- FAILED.`

Unable to solve this issue

**Comment by aim26** [comment]
I tried 5.0.3 and 5.1.1 and always errors. I tool Oculus UE fork 5.0.3 from here and biuld with it, but still no success. 
Oculus UE fork 5.0.3 bulding crashes with error:
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Could not find definition for module 'OculusInput', (referenced via Target -> OculusHandPoseRecognition.Build.cs)	HandGameplay	.....\HandGameplayTest\Intermediate\ProjectFiles\UnrealBuildTool	1

**Comment by GlebShikovec** [comment]
Seems like this sample works only with ue 4.27. But you can run sample project and use OculusHandTools plugin from UE5.1.1 meta fork: https://github.com/Oculus-VR/UnrealEngine/tree/oculus-5.1/Samples/Oculus/HandPoseShowcase
Plugin: https://github.com/Oculus-VR/UnrealEngine/tree/oculus-5.1/Samples/Oculus/HandPoseShowcase/Plugins/OculusHandTools
For me plugin also works with UE5.1.1 launcher build, if you don't need meta fork features
Do not forget to enable MetaXR plugin in project settings

**Comment by jasonmeisel** [comment]
As of [v1.1](https://github.com/oculus-samples/Unreal-HandGameplay/tree/v1.1), this project works in Unreal Engine 5!

Feel free to re-open this issue (or create a new issue) if you have any problems.
