### ISSUE TITLE
OpenXR support

### ISSUE THREAD

**Issue by mateosss** [oculus-samples/Unreal-HandGameplay#14]
Do these components work with any device supporting OpenXR or do they require specific SDKs from Oculus/Meta that would make these examples unusable in other headsets?

**Comment by jasonmeisel** [comment]
Some of the components in this project are using the `OculusXRInput` module from the [Meta XR Plugin](https://www.unrealengine.com/marketplace/en-US/product/8313d8d7e7cf4e03a33e79eb757bccba), so they won't work with other headsets by default. However, you could adapt the components to use OpenXR APIs instead.
