### ISSUE TITLE
Interactable grab pose

### ISSUE THREAD

**Issue by DarioMaciel** [oculus-samples/Unreal-HandGameplay#16]
How do I get the relative transform in the interactable grab pose?
I know hot to override the hand pose to apply a mesh that can visually match the object that is grabbing but i cant figure how to get this relative transform value.
I tried attaching a child actor to the brick and setting the actor of the tutorial hand, but the transform does not apply correctly.
I tried also to attach a static mesh to be child of the hand and apply the relative transform and still dont match 
![Capturar](https://github.com/oculus-samples/Unreal-HandGameplay/assets/19510145/ea03d3a6-6fc5-4522-b6d2-59f927a47a63)
I want to know if there is a visual way of getting this relative transform of the grab pose, if i can somehow move the mesh around and get the transform of it and apply here
for example, this rotation below dont match the rotation above (original from the project)
![Capturar2](https://github.com/oculus-samples/Unreal-HandGameplay/assets/19510145/de85c6a8-0778-4189-ae13-a715437d302c)

**Comment by jasonmeisel** [comment]
Unfortunately, there's no built-in way to do this. However, you could write a tool for this using the methods in [TransformString.h](https://github.com/oculus-samples/Unreal-HandGameplay/blob/4b436447edc0fc24adf32753b6f7a7a5e04b7047/Plugins/OculusHandTools/Source/OculusInteractable/Private/TransformString.h#L18).
