### ISSUE TITLE
GenerateProjectFiles gives missing files error

### ISSUE THREAD

**Issue by wetoo-cando** [oculus-samples/Unreal-HandGameplay#18]
Hi!

I cloned the Oculus fork of UE from here: https://github.com/Oculus-VR/UnrealEngine
Checked out branch oculus-5.3.

Also cloned the main branch of: https://github.com/oculus-samples/Unreal-HandGameplay

Then tried to run `.\GenerateProjectFiles.bat -Game HandGameplay -Engine <full path to Unreal-HandGameplay directory>\HandGameplay.uproject` in the UE root dir.

However I get `GenerateProjectFiles ERROR: It looks like you're missing some files that are required in order to generate projects.  Please check that you've downloaded and unpacked the engine source code, binaries, content and third-party dependencies before running this script.`

I have Visual Studio 2022 Community installed. 

Does anyone know what the problem could be?

**Comment by AlexThiv** [comment]
In the Engine directory did you run the ./Setub.bat file?
See step 3 on the engine setup steps: https://github.com/Oculus-VR/UnrealEngine?tab=readme-ov-file#windows

Try this and then generate the project files. Let us know if that works out for you.

**Comment by wetoo-cando** [comment]
Thanks @AlexThiv, after running setup.bat, I no longer have the above error.
