### ISSUE TITLE
Required engine version?

### ISSUE THREAD

**Issue by emretanirgan** [oculus-samples/Unreal-HandGameplay#2]
Maybe I missed it in the readme, but is there a specific version of the engine this project works with? I've tried opening it with 4.27 (both the default 4.27 as well as the Oculus branch) and 4.26, but the .uasset files weren't being recognized by the engine. If I just import the plugin to a project, the blueprints seem to show up fine. Thanks!

**Comment by gabryelx** [comment]
It only worked for me with the latest version of the Oculus branch, no other versions.  It really should say that in the readme.  Have you doublechecked that you have the latest commits?

**Comment by jasonmeisel** [comment]
@emretanirgan If the uasset files weren't being recognized, my guess is you don't have Git LFS enabled. Try running `git lfs init` in a terminal, then re-clone the repository. Let me know if that fixes it for you.

@gabryelx This project should run in Epic's 4.27. The `HandTrackingFilterComponent` does require the Oculus branch to function, but it should still build and run properly (while [logging an error](https://github.com/oculus-samples/Unreal-HandGameplay/blob/58039a22a01c9a6082d668e234a0e7f9be62283c/Plugins/OculusHandTools/Source/HandTrackingFilter/HandTrackingFilterComponent.cpp#L22)). The project does need to be built as a C++ project either way. If you can't get it working with Epic's branch, please post any logs on the failure.

**Comment by gabryelx** [comment]
> 
@jasonmeisel Thanks for the clarification, it was not working for me with the 4.27 binary, it would load but VRPIE would crash the editor referencing something in the OculusHMD.cpp.  The instructions don't reference the need to be built as a C++ project to use the Showcase; they simply say: _To try the showcase, simply load the project in the Unreal Editor, build, and launch!_  

Perhaps you can update the readme?  It wasn't obvious to me.
