### ISSUE TITLE
[REQ] Direct widget interaction using fingers

### ISSUE THREAD

**Issue by LipcaCZ** [oculus-samples/Unreal-HandGameplay#20]
Please add a demo, how to make interaction with widgets using fingers (no widget interaction "laser pointer"), as this does not work "by default" and it's very difficult to find proper tutorial for that. Thank you.

**Comment by motorsep** [comment]
I second that! Such example would be greatly appreciated.

**Comment by charan-vendra** [comment]
I second that too!

**Comment by leweaver** [comment]
Thanks for the feature request - this is something we are looking at, though it may exist as a new sample. We will update this issue when we can share more!
