### ISSUE TITLE
Errors compiling plugins for UE 5.4.2

### ISSUE THREAD

**Issue by Thomas-CASTELLANO** [oculus-samples/Unreal-HandGameplay#23]
Hello,

I tried to use the plugins **OculusHandTools** and **OculusUtils** in a **UE 5.4.2** project, but Unreal couldn't compile. 
I found some ways to resolves them though and told myself this could help.  

When I tried to compile manually with VS I had these errors :
![Capture d'écran 2024-07-04 103531](https://github.com/oculus-samples/Unreal-HandGameplay/assets/166022660/445e8391-cff6-4a2d-b264-e182189aee9b)

The include error is because the **release version of the plugins (v1.1)  isn't updated for UE 5.4**. 
To resolve this, I simply picked the plugins files **from the cloned project** instead (which was updated for 5.4 according to the commit history). Is it possible to update the release or change the misguiding readme ?

The **"static_assert_failed"** error came from **HandGesture.cpp line 243**, I just commented the UE_LOG because i'm not sure how to fix this. It seems to be the %c formating that causing trouble here.

![image](https://github.com/oculus-samples/Unreal-HandGameplay/assets/166022660/3ff4ead7-6f28-4025-a756-e36aa1c396cf)

**Comment by mluogh** [comment]
I also ran into the same issue and did the same fix of using plugins from the cloned file.

You can fix by wrapping '>' to TCHAR('>') and the same with ' ' in line 244.

**Comment by jasonmeisel** [comment]
Thanks for the heads up on both issues! They should be resolved as of latest :)
