### ISSUE TITLE
Initialize physics has bone name bug.

### ISSUE THREAD

**Issue by KutlayTunc** [oculus-samples/Unreal-HandGameplay#24]
Initialize physics for hand creates collision cylinders for bones but some naming conflict causes bug for all. 

For example. Since "index 01" is written instead of "index_01", there is no corresponding bone in the name query, so they accumulate in the root bone.

**Comment by jasonmeisel** [comment]
I'm a bit confused by your phrasing. Are you attempting to add collision cylinders to the hand bones? Where are you seeing "index 01" written instead of "index_01"?
