### ISSUE TITLE
How to get Pose Strings

### ISSUE THREAD

**Issue by mediaruebe** [oculus-samples/Unreal-HandGameplay#3]
In all of the documentation for this project "Pose Strings" are referenced. For example when you want to grab an object, it has the pose of the hand in the grab state in a "Pose String". But how can you create your own? And why not use pose assets (Unreal Animation Assets) for this?

**Comment by els-oculus** [comment]
You can find this documented here:
https://github.com/oculus-samples/Unreal-HandGameplay/blob/main/Plugins/OculusHandTools/README_HandPoseRecognition.md

The pose string is directly related to bone angles as returned by the Oculus API and has been created to demonstrate how it could be used to recognize both hand poses, and hand poses over time (simple gestures).
