### ISSUE TITLE
[UE4.27.2] Getting Crashed on editor VR mode. 

### ISSUE THREAD

**Issue by westside** [oculus-samples/Unreal-HandGameplay#6]
* Any suggestion to resolve this issue? 

I've cleaned the project and removed IIntermediate folders but nothings work.
```
Assertion failed: InOutSizeX != 0 && InOutSizeY != 0 [File:D:/Build/++UE4/Sync/Engine/Plugins/Runtime/Oculus/OculusVR/Source/OculusHMD/Private/OculusHMD.cpp] [Line: 1467]
```

**Comment by westside** [comment]
When I select view port and back to VR preview solves the problem temporally. 

![image](https://user-images.githubusercontent.com/1837913/156491269-4b1a06ad-7d1f-4545-953d-3eb1be3b81fd.png)

**Comment by Airinfinite** [comment]
So, have you solved it? I also had the same problem.

**Comment by Airinfinite** [comment]
Could you tell me how you solved this problem?
