### ISSUE TITLE
Network Replication

### ISSUE THREAD

**Issue by walid-chekkouri** [oculus-samples/Unreal-HandGameplay#9]
Hi,
 I'm testing the demo and I noticed that it's not networked, is this by design?
If yes, what do you recommend as the best approach to make it fully networked?

Thanks

**Comment by pr0-zac** [comment]
Correct, this sample is not network enabled.

I recommend looking at [Unreal-SharedSpaces](https://github.com/oculus-samples/Unreal-SharedSpaces) and [Epic's Replication documentation](https://docs.unrealengine.com/4.27/en-US/InteractiveExperiences/Networking/Actors/).
